export const data = [
  {
    service: "Eye Lash Extension",
    serviceId: 1,
    id: Date.now(),
    name: "Classic Full Set",
    image: "",
    info: "",
    time: "Two Hours",
    price: 130,
  },
  {
    service: "Eye Lash Extension",
    serviceId: 1,
    id: Date.now(),
    name: "Classic 2.0 Full Set",
    image: "",
    info: "",
    time: "Two Hours",
    price: 140,
  },
  {
    service: "Eye Lash Extension",
    serviceId: 1,
    id: Date.now(),
    name: "Hybrid Full Set",
    image: "",
    info: "",
    time: "Two Hours and 50 Minutes",
    price: 150,
  },
  {
    service: "Eye Lash Extension",
    serviceId: 1,
    id: Date.now(),
    name: "Volume Full Set",
    image: "",
    info: "",
    time: "Three Hours",
    price: 170,
  },
  {
    service: "Eye Lash Extension",
    serviceId: 1,
    id: Date.now(),
    name: "Mega Volume Full Set",
    image: "",
    info: "",
    time: "Three Hours 15 Minutes",
    price: 190,
  },
  {
    service: "Lash Fills",
    serviceId: 2,
    id: Date.now(),
    name: "Classic Express",
    duration: "1 week ",
    image: "",
    info: "",
    time: "45 Minutes",
    price: 45,
  },
  {
    service: "Lash Fills",
    serviceId: 2,
    id: Date.now(),
    name: "Classic Pick-Me-Up",
    duration: "2 week ",
    image: "",
    info: "",
    time: "1 Hour",
    price: 55,
  },
  {
    service: "Lash Fills",
    serviceId: 2,
    id: Date.now(),
    name: "Classic Fill-Me-Up",
    duration: "3 week",
    image: "",
    info: "",
    time: "1 Hour and 10 Minutes",
    price: 65,
  },
  {
    service: "Lash Fills",
    serviceId: 2,
    id: Date.now(),
    name: "Classic 2.0 Express Fill",
    duration: "1 week",
    image: "",
    info: "",
    time: "45 Minutes",
    price: 50,
  },
  {
    service: "Lash Fills",
    serviceId: 2,
    id: Date.now(),
    name: "Classic 2.0 Pick-Me-Up",
    duration: "2 week",
    image: "",
    info: "",
    time: "1 Hour 10 Minutes",
    price: 60,
  },
  {
    service: "Lash Fills",
    serviceId: 2,
    id: Date.now(),
    name: "Classic 2.0 Fill-Me-Up",
    duration: "3 week",
    image: "",
    info: "",
    time: "1 Hour 10 Minutes",
    price: 70,
  },
  {
    service: "Lash Fills",
    serviceId: 2,
    id: Date.now(),
    name: "Hybrid Express",
    duration: "1 week",
    image: "",
    info: "",
    time: "1 Hour",
    price: 55,
  },
  {
    service: "Lash Fills",
    serviceId: 2,
    id: Date.now(),
    name: "Hybrid Pick-Me-Up",
    duration: "2 week",
    image: "",
    info: "",
    time: "1 Hour 40 Minutes",
    price: 75,
  },
  {
    service: "Lash Fills",
    serviceId: 2,
    id: Date.now(),
    name: "Hybrid Fill-Me-Up",
    duration: "3 week",
    image: "",
    info: "",
    time: "1 Hour 50 Minutes",
    price: 85,
  },
  {
    service: "Lash Fills",
    serviceId: 2,
    id: Date.now(),
    name: "Volume Express",
    duration: "1 week",
    image: "",
    info: "",
    time: "1 Hour 15 Minutes",
    price: 55,
  },
  {
    service: "Lash Fills",
    serviceId: 2,
    id: Date.now(),
    name: "Volume Pick-Me-Up",
    duration: "2 week",
    image: "",
    info: "",
    time: "1 Hour 40 Minutes",
    price: 80,
  },
  {
    service: "Lash Fills",
    serviceId: 2,
    id: Date.now(),
    name: "Volume Fill-Me-Up",
    duration: "3 week",
    image: "",
    info: "",
    time: "1 Hour 50 Minutes",
    price: 75,
  },
  {
    service: "Lash Fills",
    serviceId: 2,
    id: Date.now(),
    name: "Mega Volume Express",
    duration: "1 week",
    image: "",
    info: "",
    time: "1 Hour 15 Minutes",
    price: 60,
  },
  {
    service: "Lash Fills",
    serviceId: 2,
    id: Date.now(),
    name: "Mega Volume Pick-Me-Up",
    duration: "2 week",
    image: "",
    info: "",
    time: "1 Hour 30 Minutes",
    price: 80,
  },
  {
    service: "Lash Fills",
    serviceId: 2,
    id: Date.now(),
    name: "Mega Volume Fill-Me-Up",
    duration: "3 week",
    image: "",
    info: "",
    time: "1 Hour 50 Minutes",
    price: 75,
  },
  {
    service: "Eyebrows",
    serviceId: 3,
    id: Date.now(),
    name: "Brow Wax & Tint",
    duration: "",
    image: "",
    info: "",
    time: "40 Minutes",
    price: 40,
  },
  {
    service: "Eyebrows",
    serviceId: 3,
    id: Date.now(),
    name: "Brow Glaze",
    duration: "",
    image: "",
    info: "",
    time: "1 Hour 10 Minutes",
    price: 85,
  },
  {
    service: "Lash Lifts ",
    serviceId: 4,
    id: Date.now(),
    name: "Lash Lift & Tint",
    duration: "",
    image: "",
    info: "",
    time: "1 Hour 10 Minutes",
    price: 100,
  },
  {
    service: "Permanent Make-Up",
    serviceId: 5,
    id: Date.now(),
    name: "Ombre Brows",
    duration: "",
    image: "",
    info: "",
    time: "4 Hours",
    price: 300,
  },
  {
    service: "Permanent Make-Up",
    serviceId: 5,
    id: Date.now(),
    name: "Ombre Touch-Up",
    duration: "",
    image: "",
    info: "",
    time: "3 Hours 45 Minutes",
    price: 175,
  },
  {
    service: "Permanent Make-Up",
    serviceId: 5,
    id: Date.now(),
    name: "Lip Blushing",
    duration: "",
    image: "",
    info: "",
    time: "3 Hours 45 Minutes",
    price: 300,
  },
  {
    service: "Permanent Make-Up",
    serviceId: 5,
    id: Date.now(),
    name: "Lip Blushing Touch-Up",
    duration: "",
    image: "",
    info: "",
    time: "3 Hours 45 Minutes",
    price: 175,
  },
];

export const trainingData = [
  {
    image: "",
    trainingID: 1,
    info: "",
    time: "5 Hours",
    price: 850,
  },
  {
    image: "",
    trainingID: 2,
    info: "",
    time: "2 Days",
    price: 1000,
  },
  {
    image: "",
    trainingID: 3,
    info: "",
    time: "3 - 5 Days",
    price: "TBD",
  },
];
